name: Issue metrics
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read

    steps:

    - name: Run issue-metrics tool for issues and prs opened in May 2024
      uses: github/issue-metrics@v3
      env:
        GH_TOKEN: ${{ secrets.FORK_TEST_1 }}
        SEARCH_QUERY: 'repo:Nabil-Abdullahi/ATest created:2024-05-01..2024-06-31 -reason:"not planned"'

    - name: Create issue for opened issues and prs
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Monthly issue metrics report for opened issues and prs
        token: ${{ secrets.FORK_TEST_1 }}
        content-filepath: ./issue_metrics.md
