name: Monthly issue metrics
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    steps:
    - name: Run issue-metrics tool
      uses: github/issue-metrics@v3
      env:
        GH_TOKEN : ${{ secrets.FORK_TEST_1 }}
        SEARCH_QUERY: 'repo:owner/repo created:2023-05-01..2024-06-31 -reason:"not planned"'

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v5
      with:
        title: Monthly issue metrics report
        token: ${{ secrets.FORK_TEST_1 }}
        content-filepath: ./issue_metrics.md
