name: Fork_Test

on: [push]

jobs:
  cell-block-one:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ secrets.TEST }}
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.FORK_TEST_1 }}
        run: |
          import os
          data = open("file", "w")
          lister = []
          for q in (os.getenv("MY_VAL")):
            lister.append(q)
            data.write(q)
          print(lister)
        shell: python
      # - name: Set env as secret 2
      #   env:
      #     MY_VALU: ${{ secrets.FORK_TEST_2 }}
      #   run: |
      #     import os
      #     data = open("file", "w")
      #     for q in (os.getenv("MY_VALU")):
      #       print(q)
      #       data.write(q)
      #   shell: python
